name: "Terraform"
description: "Terraform plan workflow"

inputs:
  terraform_workspace:
    description: "The Terraform workspace to use"
    default: "default"
    required: false
  terraform_version:
    description: "The Terraform version to use"
    default: "0.12.28"
    required: false
  github_token:
    description: "The GitHub token to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: Terraform Init
      id: init
      env:
        TF_WORKSPACE: ${{ inputs.terraform_workspace }}
      shell: bash
      run: terraform init
    - name: Terraform Plan
      id: plan
      env:
        TF_WORKSPACE: ${{ inputs.terraform_workspace }}
      shell: bash
      run: terraform plan -no-color || true
    - name: Find Comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: "Bot Ref: 8643624023-${{ inputs.terraform_workspace }}"
    - name: Set current date as env variable
      if: github.event_name == 'pull_request'
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: "YYYY-MM-DD HH-mm-ss"
    - name: Create or Update comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### Terraform Plan (${{ inputs.terraform_workspace }})
          #### Terraform Initialization ${{ steps.init.exitcode == 0 && 'success! ✅' || 'failed! ❌' }}
          #### Terraform Plan ${{ steps.plan.exitcode == 0 && 'success! ✅' || 'failed! ❌' }}

          <details><summary>Show Result</summary>

          ```terraform
          ${{ steps.plan.outputs.stdout }}
          ${{ steps.plan.outputs.stderr }}
          ```

          </details>

          *Pusher: `@${{ github.actor }}`, Action: `${{ github.event_name }}`*
          *Build: [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})*
          *Bot Ref: 8643624023-${{ inputs.terraform_workspace }}*
          *Time: ${{ steps.time.outputs.time }}*
        reactions: rocket
        edit-mode: replace
    - name: Terraform Plan Status
      shell: bash
      if: steps.plan.outcome == 'failure'
      run: exit 1
