name: "Terraform"
description: "Terraform apply workflow"

inputs:
  terraform_workspace:
    description: "The Terraform workspace to use"
    default: "default"
    required: false
  terraform_version:
    description: "The Terraform version to use"
    default: "0.12.28"
    required: false
  github_token:
    description: "The GitHub token to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: terraform-apply
      with:
        path: ./.terraform
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}-${{ inputs.terraform_workspace }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}-${{ inputs.terraform_workspace }}
          ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}-
          ${{ runner.os }}-${{ env.cache-name }}-
          ${{ runner.os }}-
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: Terraform Init
      id: init
      env:
        TF_WORKSPACE: ${{ inputs.terraform_workspace }}
      shell: bash
      run: |
        echo "terraform init"
        set +e
        result=$(terraform init)
        result="${result//$'\\n'/''}"
        code=$?
        set -e
        echo "${result}"
        echo "::set-output name=exit_code::${code}"
    - name: Terraform Apply
      id: apply
      shell: bash
      run: |
        echo "terraform apply -auto-approve"
        set +e
        result=$(terraform apply -auto-approve)
        result="${result//$'\\n'/''}"
        code=$?
        set -e
        echo "${result}"
        echo "::set-output name=exit_code::${code}"
    - name: Find Comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: "Bot Ref: 8643624073-${{ inputs.terraform_workspace }}"
    - name: Set current date as env variable
      if: github.event_name == 'pull_request'
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: "YYYY-MM-DD HH-mm-ss"
    - name: Create or Update comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### Terraform Apply
          #### Terraform Init ${{ steps.init.outputs.exit_code == 0 && 'succeeded! ✅' || 'failed! ❌' }}
          #### Terraform Apply ${{ steps.apply.outputs.exit_code == 0 && 'succeeded! ✅' || 'failed! ❌' }}

          *Pusher: `@${{ github.actor }}`, Action: `${{ github.event_name }}`*
          *Build: [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})*
          *Bot Ref: 8643624073-${{ inputs.terraform_workspace }}*
        reactions: rocket
        edit-mode: replace
    - name: Terraform Apply Status
      shell: bash
      run: exit ${{ steps.apply.outputs.exit_code || steps.init.outputs.exit_code }}
