name: "Version Tag"
description: "Bump the version of the project"

inputs:
  tag_type:
    description: "The type of bump to perform"
    required: false
    default: "patch"
  tag_message:
    description: "The message to use when tagging the version"
    required: false
    default: "Bump version"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
        fetch-depth: 0
    - name: Version tag
      shell: bash
      run: |
        VERSION=`git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1) 2> /dev/null`
        if [ -z "$VERSION" ]; then
            echo "No tag found!"
            TAG="1.0.0"
        else
            major="${VERSION%%.*}"; VERSION="${VERSION#*.}"
            minor="${VERSION%%.*}"; VERSION="${VERSION#*.}"
            patch="${VERSION%%.*}"; VERSION="${VERSION#*.}"
            if [ "${{ inputs.tag_type }}" = "patch" ]; then
                patch=$((patch+1))
            fi
            if [ "${{ inputs.tag_type }}" = "minor" ]; then
                minor=$((minor+1))
            fi
            if [ "${{ inputs.tag_type }}" = "major" ]; then
                major=$((major+1))
            fi
            TAG="$major.$minor.$patch"
        fi
        if [ -z "$(git describe --contains $TAG 2> /dev/null)" ]; then
            echo "Tagging Version $TAG"
            git tag -a $TAG -m "${{ inputs.tag_message }}"
            git push "https://$GITHUB_ACTOR:$GIT_ACCESS_TOKEN@github.com/$GITHUB_REPOSITORY.git" $TAG -f
        else
            echo "Version already Bumped!"
        fi
