name: "Terraform"

on:
  workflow_call:
    inputs:
      terraform_workspace:
        description: "The Terraform workspace to use"
        default: "default"
        required: false
        type: string
      terraform_version:
        description: "The Terraform version to use"
        default: "0.12.28"
        required: false
        type: string
    secrets:
      github_token:
        description: "The GitHub token to use"
        required: true
        type: string

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}
        continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform select workspace
        id: workspace
        run: terraform workspace select ${{ inputs.terraform_workspace }}
      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.29.0
      - name: Init TFLint
        run: tflint --init
      - name: Run TFLint
        id: lint
        uses: mathiasvr/command-output@v1
        with:
          run: tflint -f compact --module
        continue-on-error: true
      - name: Find Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Bot Ref: 6904391964"
      - name: Set current date as env variable
        id: time
        if: github.event_name == 'pull_request'
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: "YYYY-MM-DD HH-mm-ss"
      - name: Create or Update comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Terraform Lint (${{ steps.time.outputs.time }})

            <details><summary>Show Result</summary>

            ```bash
            ${{ steps.lint.outputs.stdout || steps.lint.outputs.stderr }}
            ```

            </details>

            *Pusher: `@${{ github.actor }}`, Action: `${{ github.event_name }}`*
            *Build: [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})*
            *Bot Ref: 6904391964*
          reactions: rocket
          edit-mode: replace
      - name: Terraform LintStatus
        if: steps.lint.outcome == 'failure'
        run: exit 1
