name: "Terraform"
description: "Terraform lint workflow"

inputs:
  terraform_workspace:
    description: "The Terraform workspace to use"
    default: "default"
    required: false
  terraform_version:
    description: "The Terraform version to use"
    default: "0.12.28"
    required: false
  github_token:
    description: "The GitHub token to use"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: Terraform Init
      id: init
      shell: bash
      run: |
        result=$(terraform init)
        exitCode=$?
        echo "::set-output name=result::$(echo $result)"
        echo "::set-output name=success::$(echo $exitCode == 0)"
    - name: Terraform select workspace
      shell: bash
      id: workspace
      run: |
        result=$(terraform workspace select ${{ inputs.terraform_workspace }})
        exitCode=$?
        echo "::set-output name=result::$(echo $result)"
        echo "::set-output name=success::$(echo $exitCode == 0)"
    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint
      with:
        tflint_version: v0.29.0
    - name: Init TFLint
      shell: bash
      run: |
        result=$(tflint --init)
        exitCode=$?
        echo "::set-output name=result::$(echo $result)"
        echo "::set-output name=success::$(echo $exitCode == 0)"
    - name: Run TFLint
      id: lint
      shell: bash
      run: |
        result=$(tflint -f compact --module)
        exitCode=$?
        echo "::set-output name=result::$(echo $result)"
        echo "::set-output name=success::$(echo $exitCode == 0)"
    - name: Find Comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: "Bot Ref: 6904391964"
    - name: Set current date as env variable
      id: time
      if: github.event_name == 'pull_request'
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: "YYYY-MM-DD HH-mm-ss"
    - name: Create or Update comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### TFLint (${{ steps.time.outputs.time }})
          #### TFLint Init ${{ steps.init.success == 'false' && 'failed! ❌' || 'succeeded! ✅' }}
          #### TFLint Lint ${{ steps.lint.success == 'false' && 'failed! ❌' || 'succeeded! ✅' }}

          <details><summary>Show Result</summary>

          ```bash
          ${{ steps.lint.outputs.result}}
          ```

          </details>

          *Pusher: `@${{ github.actor }}`, Action: `${{ github.event_name }}`*
          *Build: [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})*
          *Bot Ref: 6904391964*
        reactions: rocket
        edit-mode: replace
    - name: Terraform LintStatus
      if: steps.lint.success == 'false'
      shell: bash
      run: exit 1
