name: "Terraform"
description: "Terraform lint workflow"

inputs:
  terraform_workspace:
    description: "The Terraform workspace to use"
    default: "default"
    required: false
  terraform_version:
    description: "The Terraform version to use"
    default: "0.12.28"
    required: false
  github_token:
    description: "The GitHub token to use"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: Terraform Init
      id: init
      env:
        TF_WORKSPACE: ${{ inputs.terraform_workspace }}
      shell: bash
      run: terraform init
    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint
      with:
        tflint_version: v0.29.0
    - name: Terraform Validate
      id: validate
      env:
        TF_WORKSPACE: ${{ inputs.terraform_workspace }}
      shell: bash
      run: terraform validate -no-color
    - name: Init TFLint
      shell: bash
      env:
        TF_WORKSPACE: ${{ inputs.terraform_workspace }}
      run: tflint --init
    - name: Run TFLint
      id: lint
      env:
        TF_WORKSPACE: ${{ inputs.terraform_workspace }}
      shell: bash
      run: tflint -f compact
