name: "Bump Version"
description: "Bump the version of the project"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
        fetch-depth: 0
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.email ""
        git config --global user.name "GitHub Actions Robot"
    - name: Bump Version
      shell: bash
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
      run: |
        if [[ "${{github.event.head_commit.message}}" =~ ^.*\((m|M)ajor\)\:.*$ ]]; then
          bash ./.github/scripts/bump-version.sh MAJOR "$(bash ./.github/scripts/generate-changelog.sh)"
        elif [[ "${{github.event.head_commit.message}}" =~ ^.*\((m|M)inor\)\:.*$ ]]; then
          bash ./.github/scripts/bump-version.sh MINOR "$(bash ./.github/scripts/generate-changelog.sh)"
        else
          bash ./.github/scripts/bump-version.sh PATCH "$(bash ./.github/scripts/generate-changelog.sh)"
        fi
