name: Label Sync

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Label Sync
        uses: srealmoreno/label-sync-action@850ba5cef2b25e56c6c420c4feed0319294682fd
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          auto-discover-repos: true
          account-type: org
          owner: inhaus-ai-limited
