name: Label Sync

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Label Sync
        uses: EndBug/label-sync@v2.3.3
        with:
          config-file: ./labels.yml
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          delete-other-labels: true
